---
data_root_path: "../dataset/raw/"            # raw data path
dataset_path: "../dataset/preprocessed/"     # preprocessed data save/load path
model_save_path: "./models/rppg/"                # model save path
#TODO : yaml에서 상대경로 가능한지 확인하기
preprocess:
  flag: False                                            # true: preprocess, false: not preprocess

  common:
    process_num: 48                                       # number of task per process for multiprocessing
    type: DIFF                                           # "DIFF" or "CONT"
    fixed_position: 1                                    # 0: face tracking, 1: fixed position
    face_detect_algorithm: 1                             # 1: face recognition, 2: FaceMesh
    larger_box_coef: 1.5
    image_size: 128                                      # cropped image size

  train_dataset:
    name: cohface                                           # dataset name
    select_data:                                         # Empty the list if you want to select all person/task/source
      flag: False                                        # False if you want to select all data
      person_list: [ ]                                   # If V4V dataset, fill in the format 'Fxxx' or 'Mxxx'
      task_list: [ ]                                     # Scenario/Task Number specified in the dataset
      source_list: [ ]                                   # Fill only in case of VIPL_HR dataset.

  test_dataset:
    name: cohface                                           # dataset name
    select_data:                                         # Empty the list if you want to select all person/task/source
      flag: False                                        # False if you want to select all data
      person_list: [ ]                                   # If V4V dataset, fill in the format 'Fxxx' or 'Mxxx'
      task_list: [ ]                                     # Scenario/Task Number specified in the dataset
      source_list: [ ]                                   # Fill only in case of VIPL_HR dataset.


wandb:
  flag: false
  project_name: rppg
  entity: daeyeolkim


fit:
  model: EfficientPhys
  type: DIFF
  time_length: 180
  overlap_interval: 0 # default 0
  img_size: 72
  train_flag: False
  eval_flag: True
  eval_interval: 100
  debug_flag: True                        # True: debug mode (load small dataset, False: normal mode
  model_save_flag: True                   # True: save model, False: not save model

  train:
    dataset: cohface
    shuffle: True
    fs: 30 #video fps
    batch_size: 8
    learning_rate: 0.009
    epochs: 15
    loss: MSE
    optimizer: AdamW
    meta:
      flag: false
      inner_optim: adam
      inner_loss: MSE
      inner_lr: 0.01

  test:
    dataset: cohface
    shuffle: False
    fs: 30 #video fps
    batch_size: 8
    vital_type: HR                             # HR or HRV
    cal_type: PEAK                              # PEAK or FFT
#    bpf: [0.75, 2.5]                            # None: None / 60~100bpm : [1, 1.67] / 45~150bpm : [0.75, 2.5]
    bpf: None                            # None: None / 60~100bpm : [1, 1.67] / 45~150bpm : [0.75, 2.5]
    metric: [ 'MAE','RMSE','MAPE','Pearson' ]
    eval_time_length: 5 # second

